# Copyright Abel Sinkovics (abel@sinkovics.hu)  2010-2011.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

INCLUDES += ../../..
LIB_DIRS += ../../../src/lib/mpllibs/metatest

include ../../../src/lib/mpllibs/metatest/test.mk

