# Copyright Abel Sinkovics (abel@sinkovics.hu)  2009 - 2011.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

build : ; echo Header only library

check : ; $(MAKE) -C test check
clean : ; $(MAKE) -C test clean
all : ; $(MAKE) -C test all

